[package]
name = "lila"
version = "0.1.0"
edition = "2024"

[dependencies]
gdk = { version = "0.9.6", package = "gdk4", features = ["v4_18"] }
gio = "0.20.11"
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_18"] }
gtk4-layer-shell = "0.5.0"
gtk4-layer-shell-sys = "0.3.0"
